#============================================================= -*-perl-*-
#
# Template::Manual::Credits
#
# AUTHOR
#   Andy Wardley  <abw@wardley.org>
#
# COPYRIGHT
#   Copyright (C) 1996-2020 Andy Wardley.  All Rights Reserved.
#
#   This module is free software; you can redistribute it and/or
#   modify it under the same terms as Perl itself.
#
#========================================================================

=encoding utf8

=head1 NAME

Template::Manual::Credits - Author and contributor credits

=head1 HISTORY

The Template Toolkit began its life as the C<Text::MetaText> module,
originally released to CPAN around 1996.  This itself was the public
manifestation of an earlier template processing system I developed
while working at Peritas (now Knowledge Pool -
http://www.knowledgepool.com/)

C<Text::MetaText> was the prototype - the one we always planned to throw
away.  It did the job well, showing us what worked and what didn't, what
was good and what was bad, and gave us some ideas about what could be
done better, given the chance to start again from scratch.

Some time late in 1998 I threw away the prototype and started work on the
Template Toolkit. By then I was working at Canon Research Centre Europe Ltd.
(CRE), involved in a general research programme related to web publishing and
dynamic content generation. The first alpha release was in June 1999, followed
by numerous more alpha and beta releases culminating in 1.00 being released on
2nd December 1999.

A month or so later, work had begun on version 2.00. The plan was to get the
template language relatively stable in version 1.00 and not worry too much
about performance or other internal matters. Then, version 2.00 would follow
to improve performance, clean up the architecture and fix anything that, with
the benefit of hindsight, we thought could be improved. As it happens, me
starting work on version 2.00 coincided with Doug Steinwand sending me his
parser variant which compiled templates to Perl code, giving a major
performance boost. As well as the speedups, there are a whole host of
significant new features in version 2.00, and a greatly improved internal
architecture. Apart from a few minor "fixups" the template directives and
language have remained the same as in version 1.00

Version 2.00 was available in beta release form in July 2000, just in time for
the 4th Perl Conference where version 1.00 was awarded "Best New Perl Module".
After another extended beta release period, version 2.00 was released on 1st
December 2000.

Version 3 has been in development ever since.

=head1 AUTHOR

Andy Wardley E<lt>abw@wardley.orgE<gt> L<http://wardley.org/>

=head1 COPYRIGHT

Copyright (C) 1996-2020 Andy Wardley.  All Rights Reserved.

The Template Toolkit is free software; you can redistribute it and/or
modify it under the same terms as Perl itself.

=head1 CONTRIBUTORS

Many people have contributed ideas, inspiration, fixes and features to
the Template Toolkit.  Their efforts continue to be very much appreciated.
Please let me know if you think anyone is missing from this list.

If you submit a patch/pull request then please make sure you add your
own name to this list and include it in the changes.

Adam Kennedy, ahollandECS, Alexey A. Kiritchun, Amiri Barksdale, Andreas Koenig,
Andy Wardley, Autrijus Tang, Axel Gerstmair, Barrie Slaymaker, Ben Tilly,
Breno G. de Oliveira, Briac PilprE<eacute>, Brian Fraser, Brian Wightman,
Bryce Harrington, Chris Dean, Chris Winters, Christian, chromatic, Colin Johnson,
Colin Keith, Craig Barratt, Darren Chamberlain, Dave Cash, Dave Cross, Dave Hodgkinson,
Dave Howorth, Dave Jacoby, David Steinbrunner, Denis F. Latypoff, Dennis Clark,
Doug, Drew Taylor, Dylan, E. Choroba, eadjei, Eric Cholet, Francois Desarmenien,
François Andriot, fREW Schmidt, gordon-fish, Guido Flohr, Hans von Lengerke,
Harald Joerg, Horst Dumcke, Ivan Krylov, Ivan Kurmanov, Jacques Germishuys,
Jason Lewis, Jay Hannah, Jens Rehsack, Jess Robinson, Jim Vaughan, John Lightsey,
John Napiorkowski, Jon Jensen, Jonas Liljegren, Jonathon Padfield, José Joaquín Atria,
Jose Luis Martinez, Josh Rosenbaum, Kenny Gatdula, Kent Fredric, Kevin M. Goess, Koenig,
Leon Brocard, Leslie Michael Orchard, Lubomir, Lyle Brooks, Marc Remy, Mark Fowler,
Martin, Matthew Somerville, Michael Fowler, Michael Stevens, Mike Schilli,
Mikhail Klyuchnikov from Positive Technologies, nataraj, Neil Bowers, Nick Hibma,
Nicolas R, Nik Clayton, Norbert Buchmüller, Paul Orrock, Paul Seamons, Paul Sharpe,
Perrin Harkins, Philippe Bruhat (BooK), Piers Cawley, Portman, Rafael Kitover,
Randal L. Schwartz, Ricardo Signes, Richard Tietjen, Robin Berjon, Rod Taylor, Schaffner,
sdeseille, Sean McAfee, Sean Zellmer, Simon, Simon Dawson, Simon Matthews, Simon Napiorkowski,
Slaven Rezic, Smylers, Stas Bekman, Stathy G. Touloumis, stefano-b, Steinwand,
Steve Peters, Swen, Thierry-Michel Barral, Thuemmler, Timmy Chan, Todd Rinaldo, Tom Delmas,
Tony Bowden, Tosh Cooey, Ville SkyttE<auml>, Vivek Khera, Wilcox, William Hardison,
Yanick Champoux, Yuri Pimenov.

=cut

# Local Variables:
# mode: perl
# perl-indent-level: 4
# indent-tabs-mode: nil
# End:
#
# vim: expandtab shiftwidth=4:
